Update main2.yml

diff --git a/.github/workflows/main2.yml b/.github/workflows/main2.yml
--- a/.github/workflows/main2.yml
+++ b/.github/workflows/main2.yml
@@ -1,30 +1,43 @@
-name: Scrape latest datav2
+name: Scrape and Commit Data
 
+# Controls when the workflow will run
 on:
-  push:
-  workflow_dispatch:
+  push:  # Triggers the workflow on a push to any branch
+  workflow_dispatch:  # Allows the workflow to be manually triggered
   schedule:
-    - cron:  '*/5 * * * *'
+    - cron: '*/5 * * * *'  # Schedules the workflow to run every 5 minutes
 
 jobs:
-  scrape:
+  scrape_and_commit:
+    # Specifies the type of virtual environment the job will run on
     runs-on: ubuntu-latest
+
     steps:
-    # Step 1: Prepare the environment
-    - name: Check out this repo
+    # Step 1: Checkout the repository
+    - name: Checkout repository
       uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-    # Step 2: Get the latest data and store it as a CSV
+      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
+
+    # Step 2: Fetch the latest data
     - name: Fetch latest data
-      run: |-        
-        curl "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv" -o usgs_most_recent.csv
-    # Step 3: Commit and push
+      run: curl "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv" -o usgs_most_recent.csv
+      # Uses curl to download data from the specified URL and saves it as usgs_most_recent.csv
+
+    # Step 3: Commit and push if there are changes
     - name: Commit and push
-      run: |-
+      run: |
         git config user.name "Automated"
         git config user.email "actions@users.noreply.github.com"
-        git add -A
+        # Sets Git configuration for the commit
+
+        git add usgs_most_recent.csv
+        # Stages the downloaded file for commit
+
         timestamp=$(date -u)
+        # Saves the current UTC time in a variable
+
         git commit -m "Latest data: ${timestamp}" || exit 0
-        git push
+        # Commits the changes with a timestamp. '|| exit 0' ensures the workflow doesn't fail if there's nothing to commit
+
+        git push origin HEAD:${{ github.ref }}
+        # Pushes the commit to the same branch that triggered the workflow
